---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.arr.radarr'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.radarr'

- name: 'Converge | toggle SSL'
  hosts: 'radarr-debian-13-enable_ssl-toggle'
  gather_facts: false
  tasks:
    - name: 'Converge | toggle SSL | apply r_pufky.arr.radarr'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.radarr'
      vars:
        radarr_cfg_enable_ssl: false
