---
###############################################################################
# Radarr Backup
###############################################################################
# Backup an existing Radarr installation.
#
# Reference:
# * https://github.com/NasKar2/freenas-backup-apps/blob/master/radarrbackup.sh

- name: 'backup | shutdown radarr for backup'
  ansible.builtin.service:
    name:  'radarr'
    state: 'stopped'

- name: 'backup | setup staging'
  ansible.builtin.file:
    path:  '{{ radarr_staging }}'
    mode:  0700
    state: 'directory'

# Include *.db-*, radarr.pid for completeness; don't restore these.
# archive only operates on paths INCLUDED in archive, hence /*
- name: 'backup | create backup'
  community.general.archive:
    path:
      - '{{ radarr_config }}/*.db'
      - '{{ radarr_config }}/*.xml'
    mode:  0700
    dest: '{{ radarr_staging }}/radarr-config.tar.gz'

- name: 'backup | retrieve backup'
  ansible.builtin.fetch:
    src:  '{{ radarr_staging }}/radarr-config.tar.gz'
    dest: '{{ radarr_local_backup }}'
    flat: true

- name: 'backup | ENCRYPTION NOTICE'
  ansible.builtin.debug:
    msg: |

      BE SURE TO ENCRYPT BEFORE COMMITING CHANGES.

      ansible-vault encrypt '{{ radarr_local_backup }}'

- name: 'backup | start radarr'
  ansible.builtin.service:
    name:  'radarr'
    state: 'started'

- name: 'backup | cleanup'
  ansible.builtin.file:
    path:  '{{ radarr_staging }}'
    state: 'absent'
