---
# yamllint disable rule:line-length
###############################################################################
# Radarr Config
###############################################################################
# Radarr is installed from source. Create systemd service and reload daemons,
# create required directories, certificates, set config, and start service.
# Service may not exist if first install.
#
# Reference:
# * https://github.com/Servarr/Wiki/blob/master/servarr/servarr-install-script.sh
# yamllint enable rule:line-length

- name: 'Config | set {{ _radarr_srv_config_dir.raw }}'
  ansible.builtin.file:
    path: '{{ _radarr_srv_config_dir.raw }}'
    owner: '{{ _radarr_srv_user.raw }}'
    group: '{{ _radarr_srv_group.raw }}'
    mode: '0775'
    recurse: '{{ _radarr_srv_permissions_recursive_enable.raw }}'
    state: 'directory'
  changed_when: false  # https://github.com/ansible/ansible/issues/32636
  become:
    '{{ true if _radarr_srv_user_data_manage_enable.raw else omit }}'
  become_user: '{{
      _radarr_srv_user.raw
      if _radarr_srv_user_data_manage_enable.raw else
      omit
    }}'

- name: 'Config | set {{ _radarr_cfg_ssl_cert_path.parsed }}'
  when: _radarr_cfg_enable_ssl.raw
  ansible.builtin.copy:
    src: '{{ _radarr_cfg_ssl_cert_path.raw }}'
    dest: '{{ _radarr_cfg_ssl_cert_path.parsed }}'
    owner: '{{ _radarr_srv_user.parsed }}'
    group: '{{ _radarr_srv_group.parsed }}'
    mode: '0640'
    force: true

- name: 'Config | remove {{ _radarr_cfg_ssl_cert_path.role }}'
  when: not _radarr_cfg_enable_ssl.raw
  ansible.builtin.file:
    dest: '{{ _radarr_cfg_ssl_cert_path.role }}'
    state: 'absent'

- name: 'Config | set {{ _radarr_cfg_update_script_path.parsed }}'
  when: not _radarr_cfg_update_mechanism.raw
  ansible.builtin.copy:
    src: '{{ _radarr_cfg_update_script_path.raw }}'
    dest: '{{ _radarr_cfg_update_script_path.parsed }}'
    owner: '{{ _radarr_srv_user.parsed }}'
    group: '{{ _radarr_srv_group.parsed }}'
    mode: '0750'
    force: true

- name: 'Config | remove {{ _radarr_cfg_update_script_path.role }}'
  when: _radarr_cfg_update_mechanism.raw
  ansible.builtin.file:
    dest: '{{ _radarr_cfg_update_script_path.role }}'
    state: 'absent'

- name: 'Config | set media root folders'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ _radarr_srv_user.parsed }}'
    group: '{{ _radarr_srv_group.parsed }}'
    mode: '{{ _radarr_srv_media_perms_folder.raw }}'
    recurse: '{{ _radarr_srv_permissions_recursive_enable.raw }}'
    state: 'directory'
  changed_when: false  # https://github.com/ansible/ansible/issues/32636
  become:
    '{{ true if _radarr_srv_user_data_manage_enable.raw else omit }}'
  become_user: '{{
      _radarr_srv_user.raw
      if _radarr_srv_user_data_manage_enable.raw else
      omit
    }}'
  loop: '{{ _radarr_srv_media_root_folders.raw }}'

- name: 'Config | set media root files'
  when: _radarr_srv_media_set_perms_file_enable.raw
  ansible.builtin.shell: >-
    find '{{ item }}'
    -type f
    -exec chmod {{ _radarr_srv_media_perms_file.raw }} {};
      chown {{ _radarr_srv_user.parsed }}:{{ _radarr_srv_group.parsed }} {} \;
  changed_when: false  # https://github.com/ansible/ansible/issues/32636
  become:
    '{{ true if _radarr_srv_user_data_manage_enable.raw else omit }}'
  become_user: '{{
      _radarr_srv_user.raw
      if _radarr_srv_user_data_manage_enable.raw else
      omit
    }}'
  loop: '{{ _radarr_srv_media_root_folders.raw }}'

# Writing the configuration back requires to_json, ansible.utils.to_xml, and
# xmltodict python3 package installed on both controller and node. Just use a
# template instead.
- name: 'Config | set Radarr configuration'
  ansible.builtin.template:
    src: 'config.xml.j2'
    dest: '{{ _radarr_srv_config_dir.parsed ~ "config.xml" }}'
    owner: '{{ _radarr_srv_user.parsed }}'
    group: '{{ _radarr_srv_group.parsed }}'
    mode: '0600'

- name: 'Config | Radarr service'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.systemd'
  vars:
    systemd_daemon_reload_enable: true
    systemd_services:
      - name: 'radarr'
        state: 'present'
        drop_in: false
        unit:
          description: 'Radarr Daemon'
          after:
            - 'syslog.target'
            - 'network.target'
        service:
          type: 'simple'
          exec_start:
            - >-
              {{ radarr_role_repo_extract_symlink ~ "/Radarr" }}
              -nobrowser
              -data={{ _radarr_srv_config_dir.raw }}
          timeout_stop_sec: 20
          restart: 'always'  # always restart for periodic service restarts
          runtime_max_sec: '{{
              "1d"
              if _radarr_srv_restart_daily_enable.raw else
              "infinity"
            }}'
        exec:
          user: '{{ _radarr_srv_user.raw }}'
          group: '{{ _radarr_srv_group.raw }}'
          u_mask: '{{ _radarr_srv_u_mask.raw }}'
        kill:
          kill_mode: 'process'
        install:
          wanted_by:
            - 'multi-user.target'
