---
# yamllint disable rule:line-length
###############################################################################
# Radarr Config
###############################################################################
# Radarr is installed from source. Create systemd service and reload daemons,
# create required directories, certificates, set config, and start service.
# Service may not exist if first install.
#
# New config.xml options must be manually added to the template.
#
# Args:
#   _radarr_uid: int - radarr user UID.
#   _radarr_gid: int - radarr user GID.
#
# Reference:
# * https://github.com/Servarr/Wiki/blob/master/servarr/servarr-install-script.sh
# yamllint enable rule:line-length

- name: 'Config | Radarr service'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.systemd'
  vars:
    systemd_daemon_reload_enable: true
    systemd_services:
      - name: 'radarr'
        state: 'present'
        drop_in: false
        unit:
          description: 'Radarr Daemon'
          after:
            - 'syslog.target'
            - 'network.target'
        service:
          type: 'simple'
          exec_start:
            - >-
              {{ radarr_role_repo_extract_symlink }}/Radarr
              -nobrowser
              -data={{ radarr_service_data_dir }}
          timeout_stop_sec: 20
          restart: 'always'  # always restart for periodic service restarts
          runtime_max_sec:
            '{{ "1d" if radarr_service_restart_daily_enable else "infinity" }}'
        exec:
          user: '{{ radarr_user }}'
          group: '{{ radarr_group }}'
          u_mask: '{{ radarr_service_u_mask }}'
        kill:
          kill_mode: 'process'
        install:
          wanted_by:
            - 'multi-user.target'

- name: 'Config | stop Radarr'
  ansible.builtin.service:
    name: 'radarr'
    state: 'stopped'

- name: 'Config | set {{ radarr_service_data_dir }}'
  ansible.builtin.include_role:
    name: 'r_pufky.lib.utils'
    tasks_from: 'remote_file.yml'
  vars:
    file_path: '{{ radarr_service_data_dir }}'
    file_owner: '{{ _radarr_uid }}'
    file_group: '{{ _radarr_gid }}'
    file_mode: '0775'
    file_recurse: '{{ radarr_service_permissions_recursive_enable }}'
    file_state: 'directory'

- name: 'Config | set {{ radarr_service_data_dir }}/radarr.pfx'
  when: radarr_config_enable_ssl  # noqa name[template] full path
  ansible.builtin.copy:
    src: '{{ radarr_config_ssl_cert_path }}'
    dest: '{{ radarr_service_data_dir }}/radarr.pfx'
    owner: '{{ radarr_user }}'
    group: '{{ radarr_group }}'
    mode: '0640'
    force: true

- name: 'Config | remove {{ radarr_service_data_dir }}/radarr.pfx'
  when: not radarr_config_enable_ssl  # noqa name[template] full path
  ansible.builtin.file:
    dest: '{{ radarr_service_data_dir }}/radarr.pfx'
    state: 'absent'

- name: 'Config | set {{ radarr_service_data_dir }}/update_script'
  when: not radarr_config_update_mechanism  # noqa name[template] full path
  ansible.builtin.copy:
    src: '{{ radarr_config_update_script_path }}'
    dest: '{{ radarr_service_data_dir }}/update_script'
    owner: '{{ radarr_user }}'
    group: '{{ radarr_group }}'
    mode: '0750'
    force: true

- name: 'Config | remove {{ radarr_service_data_dir }}/update_script'
  when: radarr_config_update_mechanism  # noqa name[template] full path
  ansible.builtin.file:
    dest: '{{ radarr_service_data_dir }}/update_script'
    state: 'absent'

# Use UID/GID as some media filesystems may be remote.
- name: 'Config | set media root folders'
  ansible.builtin.include_role:
    name: 'r_pufky.lib.utils'
    tasks_from: 'remote_file.yml'
  vars:
    file_path: '{{ item }}'
    file_owner: '{{ _radarr_uid }}'
    file_group: '{{ _radarr_gid }}'
    file_mode: '{{ radarr_media_perms_folder }}'
    file_recurse: '{{ radarr_service_permissions_recursive_enable }}'
    file_state: 'directory'
  loop: '{{ radarr_media_root_folders }}'

# Use UID/GID as some media filesystems may be remote.
- name: 'Config | set media root files'
  when: radarr_media_set_perms_file_enable
  ansible.builtin.shell: >-
    find '{{ item }}'
    -type f
    -exec chmod {{ radarr_media_perms_file }} {};
      chown {{ _radarr_uid }}:{{ _radarr_gid }} {} \;
  changed_when: false
  loop: '{{ radarr_media_root_folders }}'

# Writing the configuration back requires to_json, ansible.utils.to_xml, and
# xmltodict python3 package installed on both controller and node. Just use a
# template instead.
- name: 'Config | set Radarr configuration'
  notify: 'Handlers | restart radarr'
  ansible.builtin.template:
    src: 'config.xml.j2'
    dest: '{{ radarr_service_data_dir }}/config.xml'
    owner: '{{ radarr_user }}'
    group: '{{ radarr_group }}'
    mode: '0600'

- name: 'Config | start Radarr'
  ansible.builtin.service:
    name: 'radarr'
    state: 'started'
