---
###############################################################################
# Radarr Install
###############################################################################
# Radarr v3
#
# Reference:
# * https://radarr.video/#downloads-v3-linux-other
# * https://github.com/Radarr/Radarr
# * https://blog.5h4d0w.net/2019/12/install-radarr-on-debian-10

- ansible.builtin.include_tasks: manage_users.yml

# Mono is included in the radarr repo, however this will install the
# latest version directly from the mono repo unless distro specific.
- name: 'install | add mono repo key'
  ansible.builtin.apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id:        '3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF'
    state:     'present'

- name: 'install | set mono version'
  ansible.builtin.set_fact:
    _radarr_mono_version: '{% if ansible_distribution_release is not in radarr_mono_supported_libraries %}{{ radarr_default_mono_library }}{% else %}stable-{{ ansible_distribution_release }}{% endif %}'

- name: 'install | add mono repo'
  ansible.builtin.apt_repository:
    repo:     'deb https://download.mono-project.com/repo/debian {{ _radarr_mono_version }} main'
    filename: 'mono'
    state:    'present'
    update_cache: true

- name: 'install | install dependencies'
  ansible.builtin.apt:
    name:  '{{ radarr_default_packages }}'
    state: 'latest'

- name: 'install | create radarr directories'
  ansible.builtin.file:
    path:  '{{ item }}'
    owner: '{{ radarr_user }}'
    group: '{{ radarr_group }}'
    mode:  0750
    state: 'directory'
  loop:
    - '{{ radarr_dir }}'
    - '{{ radarr_config }}'

- name: 'install | check install binary'
  ansible.builtin.stat:
    path: '{{ radarr_dir }}/Radarr.exe'
  register: _radarr_binary

- name: 'install | get radarr'
  ansible.builtin.get_url:
    url:    'https://radarr.servarr.com/v1/update/master/updatefile?os={{ radarr_arch_c }}&runtime=netcore&arch={{ radarr_arch_generic }}'
    dest:   '/tmp/radarr.tar.gz'
    mode:   0644
    owner:  '{{ radarr_user }}'
    group:  '{{ radarr_group }}'
  when: not _radarr_binary.stat.exists

- name: 'install | install'
  ansible.builtin.unarchive:
    src:        '/tmp/radarr.tar.gz'
    remote_src: true
    dest:       '{{ radarr_dir }}'
    creates:    '{{ radarr_dir }}/Radarr.exe'
    owner:      '{{ radarr_user }}'
    group:      '{{ radarr_group }}'
    mode:       'o-rwx'
    # Remove the leading 'Radarr/' directory in the archive
    extra_opts: '--strip-components=1'
  when: not _radarr_binary.stat.exists
  notify: 'restart radarr'

- name: 'install | set configuration'
  ansible.builtin.template:
    src:   'config.xml.j2'
    dest:  '{{ radarr_config }}/config.xml'
    owner: '{{ radarr_user }}'
    group: '{{ radarr_group }}'
    mode:  0600 #0664 originally
  notify: 'restart radarr'

- name: 'install | restart radarr service daily'
  ansible.builtin.cron:
    name:         'restart radarr service daily'
    special_time: 'daily'
    user:         'root'
    job:          'service radarr restart'
    state:        'present'

- name: 'install | set /etc/systemd/system/radarr.service'
  ansible.builtin.template:
    src:   'radarr.service.j2'
    dest:  '/etc/systemd/system/radarr.service'
    owner: 'root'
    group: 'root'
    mode:  0644
  notify:
    - 'reload systemd'
    - 'restart radarr'
