---
###############################################################################
# Radarr Prep
###############################################################################
# *arr services use the same codebase; any bugs or fixes should be checked for
# all related services.

- name: 'Prep | assert database requirements'
  when: _radarr_cfg_database_type.raw == 'postgres'
  ansible.builtin.assert:
    quiet: true
    that:
      - _radarr_cfg_database_host.raw | length > 0
      - _radarr_cfg_database_port.raw > 0
      - _radarr_cfg_database_user.raw | length > 0
      - _radarr_cfg_database_password.raw | length > 0
      - _radarr_cfg_database_main.raw | length > 0
      - _radarr_cfg_database_log.raw | length > 0
    fail_msg: >
      ✘ radarr_cfg_database_type=postgres requires all options set.

          radarr_cfg_database_host: '{{ _radarr_cfg_database_host.raw }}'
          radarr_cfg_database_port: '{{ _radarr_cfg_database_port.raw }}'
          radarr_cfg_database_user: '{{ _radarr_cfg_database_user.raw }}'
      radarr_cfg_database_password: '{{ _radarr_cfg_database_password.raw }}'
          radarr_cfg_database_main: '{{ _radarr_cfg_database_main.raw }}'
           radarr_cfg_database_log: '{{ _radarr_cfg_database_log.raw }}'

- name: 'Prep | assert SSL requirements'
  when: _radarr_cfg_enable_ssl.raw
  ansible.builtin.assert:
    quiet: true
    that:
      - _radarr_cfg_ssl_cert_path.raw | length > 0
    fail_msg: >
      ✘ radarr_cfg_enable_ssl=true requires
      radarr_cfg_ssl_cert_path set.

      radarr_cfg_ssl_cert_path: '{{ _radarr_cfg_ssl_cert_path.raw }}'

- name: 'Prep | assert update script requirements'
  when: not _radarr_cfg_update_mechanism.raw
  ansible.builtin.assert:
    quiet: true
    that:
      - _radarr_cfg_update_script_path.raw | length > 0
    fail_msg: >
      ✘ radarr_cfg_update_mechanism=false requires
      radarr_cfg_update_script_path set.

      radarr_cfg_update_script_path: '{{ _radarr_cfg_update_script_path.raw }}'

- name: 'Prep | manage users'
  when: _radarr_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ radarr_role_user }}'
    users_role_group: '{{ radarr_role_group }}'

- name: 'Prep | enumerate system user {{ _radarr_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _radarr_srv_user.raw }}'
  check_mode: true
  changed_when: false
  register: _radarr_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _radarr_srv_user: '{{
        _radarr_srv_user |
        combine({"role_uid": _radarr_srv_user_query.uid})
      }}'
    _radarr_srv_group: '{{
        _radarr_srv_group |
        combine({"role_gid": _radarr_srv_user_query.group})
      }}'

- name: 'Prep | stop services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
  failed_when: false
  loop:
    - 'radarr.service'
