---
###############################################################################
#  Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.
#
# *arr services use the same codebase; any bugs or fixes should be checked for
# all related services.

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    radarr__srv: "{{ radarr___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _user=radarr_srv_user,
        _group=radarr_srv_group,
      ) }}"
    radarr__cfg: "{{ {} | r_pufky.data.v3(

        _version=radarr_srv_version,
        _package=(
          'Radarr.master.' ~ radarr_srv_version[1:] ~ '.linux-core-x64.tar.gz'
        ),
        _app_d='/opt/radarr/src/' ~ radarr_srv_version,
        _url=(
          radarr___repo_url ~ radarr_srv_version ~ '/' ~
          'Radarr.master.' ~ radarr_srv_version[1:] ~ '.linux-core-x64.tar.gz'
        ),
        _d=radarr_cfg_d | regex_replace('\\/$', ''),
        _backup_d=radarr_cfg_backup_d | regex_replace('\\/$', ''),
        _backup_metadata=radarr_cfg_backup_metadata,
      ) }}"

- name: 'Prep | assert | backup enabled and location defined'
  when: radarr_flg_backup
  ansible.builtin.assert:
    quiet: true
    that:
      - radarr__cfg._backup_d | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      radarr_flg_backup: {{ radarr_flg_backup }}
      radarr_cfg_backup_d: {{ radarr__cfg._backup_d }}

- name: 'Prep | assert | restore enabled and location defined'
  when: radarr_flg_restore
  ansible.builtin.assert:
    quiet: true
    that:
      - radarr__cfg._backup_d | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      radarr_flg_restore: {{ radarr_flg_restore }}
      radarr_cfg_backup_d: {{ radarr__cfg._backup_d }}

- name: 'Prep | assert | config enabled and source defined'
  when: radarr_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - radarr__cfg._d | length > 0
    fail_msg: |

      ✘ Config source not set.
      Config source enabled but no config source defined.

      radarr_flg_config: {{ radarr_flg_config }}
      radarr_cfg_d: {{ radarr__cfg._d }}

- name: '{{ "Prep | account | query user " ~ radarr__srv._user }}'
  ansible.builtin.command: '{{ "id " ~ radarr__srv._user }}'
  failed_when: false
  register: radarr__cfg_check
  changed_when: radarr__cfg_check.rc > 0

- name: '{{ "Prep | account | query group " ~ radarr__srv._group }}'
  ansible.builtin.command: '{{ "groups " ~ radarr__srv._group }}'
  failed_when: false
  register: radarr__group_check
  changed_when: radarr__group_check.rc > 0

- name: '{{ "Prep | account | create group " ~ radarr__srv._group }}'
  when: radarr__group_check.rc != 0
  ansible.builtin.group:
    gid: '{{ radarr___group.gid }}'
    name: '{{ radarr___group.name }}'
    state: 'present'

- name: '{{ "Prep | account | create user " ~ radarr__srv._user }}'
  when: radarr__cfg_check.rc != 0
  ansible.builtin.user:
    name: '{{ radarr___user.name }}'
    group: '{{ radarr___user.group }}'
    uid: '{{ radarr___user.uid }}'
    shell: '{{ radarr___user.shell }}'
    home: '{{ radarr___user.home }}'
    create_home: '{{ radarr___user.create_home }}'
    password: '{{ radarr___user.password }}'
    password_lock: '{{ radarr___user.password_lock }}'
    update_password: '{{ radarr___user.update_password }}'
    expires: '{{ radarr___user.expires }}'
    system: '{{ radarr___user.system }}'

# Pre-existing users may have a different UID/GID/Home.
- name: '{{ "Prep | account | enumerate " ~ radarr__srv._user }}'
  ansible.builtin.user:
    name: '{{ radarr__srv._user }}'
  check_mode: true
  changed_when: false
  register: radarr__cfg_query

- name: 'Prep | fact | parse service UID/GID'
  ansible.builtin.set_fact:
    radarr__cfg: "{{ radarr__cfg | r_pufky.data.v3(

        _uid=radarr__cfg_query.uid,
        _gid=radarr__cfg_query.group,
      ) }}"

- name: 'Prep | systemd | stop radarr.service'
  ansible.builtin.systemd:
    name: 'radarr.service'
    state: 'stopped'
  failed_when: false
