---
###############################################################################
# Default
###############################################################################
# Default configuration is deployed successfully using postgres. Configuration
# should succeed with and without radarr_srv_user_data_manage_enable.
#
# Tests:
# * Same testing requirements as default.
# * config.xml set.
# * radarr.service active and running.
# * /data/radarr/config created with correct permissions.
# * /data/media created with correct permissions.
# * /data/media - file permissions recursively set with correct permissions.
# * /data/radarr/config/update_script does not exist.
# * /data/radarr/config/radarr.pfx does not exist.
# * Postgres backed instance launches correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        radarr_srv_media_root_folders: ['/data/media']
        radarr_cfg_api_key: 'abcdef1234567890abcdef1234567890'
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'default'
            version: 'v5.28.0.10274'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/" ~
                "Radarr.master.5.28.0.10274.linux-core-x64.tar.gz"
              }}'
        radarr_cfg_database_type: 'postgres'
        radarr_cfg_database_host: 'localhost'
        radarr_cfg_database_password: 'test'
    host_vars:
      radarr-debian-13-postgres_user_data:
        radarr_srv_user_data_manage_enable: true
platforms:
  - name: 'radarr-debian-13-postgres'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
  - name: 'radarr-debian-13-postgres_user_data'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
