---
###############################################################################
# Radarr Database Options
###############################################################################
# Existing databases are migrated automatically when new versions are
# installed. Migration between database platforms is not supported and must be
# done manually.

# Database backend.
#
# Values:
#   postgres: Postgres 14+. HIGHLY recommended.
#     sqlite: Sqlite3 (default).
#
# Default: 'sqlite'.
radarr_cfg_database_type: 'sqlite'

###############################################################################
# PostgreSQL Database Options
###############################################################################
# Postgres requires pre-existing databases with root privileges to initialize
# tables and manage migrations. Postgres databases are NOT backed up by Radarr.
#
# Manual Migration Overview:
# * Create postgres databases.
# * systemctl stop radarr
# * sqlite3 radarr.db vacuum
# * Update config.xml with DB settings (or re-apply role with postgres).
# * systemctl start radarr
# * Confirm radarr running (appears empty).
# * systemctl stop radarr
# * cp radarr.db postgres:/tmp
# * chmod o+r /tmp/radarr.db
# * Install pgloader to /usr/local/bin
# * Login to postgres: psql -d radarr
# * Remove auto-generated tables (see reference).
# * Execute pgloader. Use 'prefetch rows' and 'batch size' options.
#   * Many WARNINGS may appear; these can be ignored.
# * systemctl start radarr
# * No migrations have needed post migration steps in practice.
# * Backup and remove sqlite3 database files.
#
# Reference:
# * https://wiki.servarr.com/en/radarr/postgres-setup
# * https://github.com/Roxedus/Pgloader-bin

# Database host. Default: 'localhost'.
radarr_cfg_database_host: 'localhost'

# Database port. Default: 5432.
radarr_cfg_database_port: 5432

# Database user. Default: 'radarr'.
radarr_cfg_database_user: 'radarr'

# Database password. Default: ''.
radarr_cfg_database_password: ''

# Main database name. Default: 'radarr-main'.
radarr_cfg_database_main: 'radarr-main'

# Log database name. Default: 'radarr-log'.
radarr_cfg_database_log: 'radarr-log'
