---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | create cache'

    - name: 'Prepare | check 5.27.5.10198'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Prepare | cache 5.27.5.10198'
        test_dest: 'Radarr.master.5.27.5.10198.linux-core-x64.tar.gz'
        test_url: '{{
            "https://github.com/Radarr/Radarr/releases/download/" ~
            "v5.27.5.10198/" ~
            "Radarr.master.5.27.5.10198.linux-core-x64.tar.gz"
          }}'
        test_mode: '0640'

- name: 'Prepare'
  hosts: 'radarr-debian-13-user_data'
  gather_facts: false
  tasks:
    - name: 'Prepare | simulate user media restriction'
      ansible.builtin.file:
        path: '/data'
        owner: 5555
        group: 5555
        mode: '0755'
        state: 'directory'
