---
- name: 'Default | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Default | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Default | prepare | create cache'

    - name: 'Default | prepare | check 5.18.4.9674'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Default | prepare | cache 5.18.4.9674'
        test_dest: 'Radarr.master.5.18.4.9674.linux-core-x64.tar.gz'
        test_url: '{{
            "https://github.com/Radarr/Radarr/releases/download/" ~
            "v5.18.4.9674/" ~
            "Radarr.master.5.18.4.9674.linux-core-x64.tar.gz"
          }}'
        test_mode: '0640'
