---
- name: 'Default | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Default | verify | query config.xml'
      ansible.builtin.copy:
        src: 'files/config.xml'
        dest: '/var/lib/radarr/config.xml'
        owner: 'media'
        group: 'media'
        mode: '0600'
      check_mode: true
      diff: true
      register: _test_radarr_config_xml

    - name: 'Default | verify | assert config.xml'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_radarr_config_xml.changed
        fail_msg: >
          /var/lib/radarr/config.xml is not in expected format:
          {{ _test_radarr_config_xml.diff }}.

    # Radarr will fail if configuration is bad (r_pufky.srv.systemd)
    - name: 'Default | verify | assert radarr.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"radarr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["radarr.service"]["state"] == "running"'
        fail_msg: 'radarr.service should be enabled and running.'

    - name: 'Default | verify | query /var/lib/radarr'
      ansible.builtin.file:
        path: '/var/lib/radarr'
        owner: 'media'
        group: 'media'
        mode: '0775'
      check_mode: true
      diff: true
      register: _test_radarr_var_lib

    - name: 'Default | verify | assert /var/lib/radarr'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_radarr_var_lib.changed
        fail_msg: >
          /var/lib/radarr should exist as 0775 media:media
          ({{ _test_radarr_var_lib.diff }}).

    - name: 'Default | verify | query /var/lib/radarr/update_script'
      ansible.builtin.file:
        path: '/var/lib/radarr/update_script'
        state: 'absent'
      check_mode: true
      register: _test_radarr_update

    - name: 'Default | verify | assert /var/lib/radarr/update_script'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_radarr_update.changed
        fail_msg: '/var/lib/radarr/update_script should not exist.'

    - name: 'Default | verify | query /var/lib/radarr/radarr.pfx'
      ansible.builtin.file:
        path: '/var/lib/radarr/radarr.pfx'
        state: 'absent'
      check_mode: true
      register: _test_radarr_pfx

    - name: 'Default | verify | assert /var/lib/radarr/radarr.pfx'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_radarr_pfx.changed
        fail_msg: '/var/lib/radarr/radarr.pfx should not exist.'

    - name: 'Default | verify | query /data/media'
      ansible.builtin.file:
        path: '/data/media'
        owner: 'media'
        group: 'media'
        mode: '0755'
      check_mode: true
      diff: true
      register: _test_radarr_data_media

    - name: 'Default | verify | assert /data/media'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_radarr_data_media.changed
        fail_msg: >
          /data/media should exist as 0755 media:media
          ({{ _test_radarr_data_media.diff }}).
