---
- name: 'Default | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Default | verify | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Default | verify | config.xml'
        test_src: 'files/config.xml'
        test_file: '/var/lib/radarr/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    # Radarr will fail if configuration is bad (r_pufky.deb.systemd)
    - name: 'Default | verify | assert radarr.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"radarr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["radarr.service"]["state"] == "running"'
        fail_msg: '✘ radarr.service should be enabled and running.'

    - name: 'Default | verify | /var/lib/radarr'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /var/lib/radarr'
        test_file: '/var/lib/radarr'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0775'
        test_state: 'directory'

    - name: 'Default | verify | /var/lib/radarr'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /var/lib/radarr/{{ item }}'
        test_file: '/var/lib/radarr/{{ item }}'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
      loop:
        - 'update_script'
        - 'radarr.pfx'

    - name: 'Default | verify | /data/media'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Default | verify | /data/media'
        test_file: '/data/media'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0755'
        test_state: 'directory'
