---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.srv.radarr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.radarr'

- name: 'Converge | toggle updates'
  hosts: 'radarr-debian-12-update_mechanisms-toggle'
  gather_facts: false
  tasks:
    - name: 'Converge | toggle updates | apply r_pufky.srv.radarr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.radarr'
      vars:
        radarr_cfg_update_mechanism: true
