---
# yamllint disable rule:line-length
- name: 'Update mechanism | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Update mechanism | verify | gather service status'
      ansible.builtin.service_facts:

    # Radarr will fail if configuration is bad (r_pufky.srv.systemd)
    - name: 'Update mechanism | verify | assert radarr.service active'
      ansible.builtin.assert:
        that:
          - '"radarr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["radarr.service"]["state"] == "running"'
        fail_msg: 'radarr.service should be enabled and running.'

- name: 'Update mechanism | verify | script enabled'
  hosts: 'radarr-debian-12-update_mechanisms'
  gather_facts: false
  tasks:
    - name: 'Update mechanism | verify | script enabled | query config.xml'
      ansible.builtin.copy:
        src: 'files/config_script.xml'
        dest: '/var/lib/radarr/config.xml'
        owner: 'media'
        group: 'media'
        mode: '0600'
      check_mode: true
      diff: true
      register: _test_radarr_config_xml

    - name: 'Update mechanism | verify | script enabled | assert config.xml'
      ansible.builtin.assert:
        that:
          - not _test_radarr_config_xml.changed
        fail_msg: >
          /var/lib/radarr/config.xml is not in expected format:
          {{ _test_radarr_config_xml.diff }}.

    - name: 'Update mechanism | verify | script enabled | query /var/lib/radarr/update_script'
      ansible.builtin.file:
        path: '/var/lib/radarr/update_script'
        owner: 'media'
        group: 'media'
        mode: '0750'
      check_mode: true
      diff: true
      register: _test_radarr_update

    - name: 'Update mechanism | verify | script enabled | assert /var/lib/radarr/update_script'
      ansible.builtin.assert:
        that:
          - not _test_radarr_update.changed
        fail_msg: >
          /var/lib/radarr/update_script should exist with 0750 media:media
          {{ _test_radarr_update.diff }}

- name: 'Update mechanism | verify | script toggled'
  hosts: 'radarr-debian-12-update_mechanisms-toggle'
  gather_facts: false
  tasks:
    - name: 'Update mechanism | verify | script toggled | query config.xml'
      ansible.builtin.copy:
        src: 'files/config_toggle.xml'
        dest: '/var/lib/radarr/config.xml'
        owner: 'media'
        group: 'media'
        mode: '0600'
      check_mode: true
      diff: true
      register: _test_radarr_config_xml

    - name: 'Update mechanism | verify | script toggled | assert config.xml'
      ansible.builtin.assert:
        that:
          - not _test_radarr_config_xml.changed
        fail_msg: >
          /var/lib/radarr/config.xml is not in expected format:
          {{ _test_radarr_config_xml.diff }}.

    - name: 'Update mechanism | verify | script toggled | query /var/lib/radarr/update_script'
      ansible.builtin.file:
        path: '/var/lib/radarr/update_script'
        state: 'absent'
      check_mode: true
      register: _test_radarr_update

    - name: 'Update mechanism | verify | script toggled | assert /var/lib/radarr/update_script'
      ansible.builtin.assert:
        that:
          - not _test_radarr_update.changed
        fail_msg: '/var/lib/radarr/update_script should not exist.'
